name: .NET Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          9.0.x

    - name: Build with dotnet
      run: dotnet build --configuration release

#    No need because all tests passed if the solution is successfully built
#    - name: Test
#      run: dotnet test --configuration release
